services:
  - type: web
    name: mlb-betting-predictions
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_production:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
